services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: brightsteps-php
    container_name: brightsteps-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - composer-cache:/tmp/composer
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8000}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-brightsteps}
      DB_USERNAME: ${DB_USERNAME:-brightsteps}
      DB_PASSWORD: ${DB_PASSWORD:-brightsteps}
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: brightsteps-web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  node:
    image: node:20-alpine
    container_name: brightsteps-node
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port ${VITE_DEV_SERVER_PORT:-5173}"
    volumes:
      - ./:/var/www/html:cached
      - node-cache:/root/.npm
    environment:
      VITE_DEV_SERVER_HOST: 0.0.0.0
      VITE_DEV_SERVER_PORT: ${VITE_DEV_SERVER_PORT:-5173}
    ports:
      - "5173:5173"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: brightsteps-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-brightsteps}
      MYSQL_USER: ${DB_USERNAME:-brightsteps}
      MYSQL_PASSWORD: ${DB_PASSWORD:-brightsteps}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  composer-cache:
  node-cache:
